# Generated by Django 3.2.5 on 2021-07-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyIndexApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='happyindextable',
            old_name='countaryName',
            new_name='countryName',
        ),
    ]
